# Generated by Django 3.1.2 on 2020-10-10 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mygallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image_url',
            field=models.CharField(default='yes', max_length=60),
            preserve_default=False,
        ),
    ]
