# Generated by Django 3.1.2 on 2020-10-11 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mygallery', '0002_image_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_url',
            field=models.ImageField(upload_to='galleries/'),
        ),
    ]
